# Generated by Django 3.0.8 on 2020-09-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='workouts',
            name='location',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workouts',
            name='image',
            field=models.TextField(max_length=300),
        ),
    ]
