# Generated by Django 3.0.8 on 2020-09-08 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plans',
            name='comments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Comments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plans',
            name='workouts',
            field=models.ManyToManyField(to='main_app.Workouts'),
        ),
        migrations.AddField(
            model_name='workouts',
            name='calories',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouts',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouts',
            name='image',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouts',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('goalWeight', models.IntegerField()),
                ('age', models.IntegerField()),
                ('plans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Plans')),
            ],
        ),
    ]
