# Generated by Django 3.0.8 on 2020-09-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='workout',
            field=models.ManyToManyField(to='main_app.Workouts'),
        ),
    ]
