# Generated by Django 3.0.8 on 2020-09-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200910_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='category',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
