# Generated by Django 3.0.8 on 2020-09-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200908_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='workouts',
        ),
        migrations.AddField(
            model_name='plans',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
