# Generated by Django 3.0.8 on 2020-09-09 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200908_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='plans',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Plans'),
            preserve_default=False,
        ),
    ]
