# Generated by Django 3.0.8 on 2020-09-09 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200909_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plans', models.ManyToManyField(to='main_app.Plans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User')),
            ],
        ),
    ]
