# Generated by Django 3.0.8 on 2020-09-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='image',
            field=models.ImageField(blank=True, upload_to='plan_image'),
        ),
    ]
